version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    stdin_open: true
    tty: true
    networks:
      - eic-network

networks:
  eic-network:
    external: true
